import type { Analysis, Content, Item } from '../shared/schemas';
export const countries:Record<string,string>={DK:'덴마크',SE:'스웨덴',NO:'노르웨이',FI:'핀란드',DE:'독일',US:'미국',KR:'대한민국',JP:'일본',CN:'중국'};
export const products:Record<string,string>={actuator:'액추에이터',controller:'컨트롤러',other:'기타'};
export function canonicalUrl(value:string){const u=new URL(value);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_/i.test(k)||['fbclid','gclid'].includes(k))u.searchParams.delete(k);u.searchParams.sort();return u.toString();}
export function youtubeId(value:string){const u=new URL(value);if(u.hostname==='youtu.be')return u.pathname.slice(1);if(['www.youtube.com','youtube.com','m.youtube.com'].includes(u.hostname))return u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([\w-]{11})/)?.[1];return undefined;}
export function dedup(type:string,url:string){const video=type==='video'?youtubeId(url):undefined;return video?`youtube:${video}`:canonicalUrl(url);}
export function classify(c:Content,profileVersion:number):Analysis{const text=`${c.title} ${c.titleKo} ${c.description}`;const p:Analysis['products']=[];if(/actuator|액추에이터|구동기/i.test(text))p.push('actuator');if(/controller|컨트롤러|제어기/i.test(text))p.push('controller');const found=Object.entries(countries).filter(([code,name])=>new RegExp(`${name}|${({DK:'Denmark|Danish',SE:'Sweden|Swedish',NO:'Norway|Norwegian',FI:'Finland|Finnish',DE:'Germany|German',US:'United States|American',KR:'South Korea|Korean',JP:'Japan|Japanese',CN:'China|Chinese'} as Record<string,string>)[code]}`,'i').test(text)).map(([code])=>code);const score=(p.length?40:0)+(found.some(x=>['DK','SE','NO','FI'].includes(x))?20:found.includes('DE')?10:0)+(/robot|로봇/i.test(text)?10:0)+(/생산 확대|조달|파트너 모집|procurement|production expansion/i.test(text)?20:/발표|launch|announce/i.test(text)?10:0);return {id:crypto.randomUUID(),contentId:c.id,analysisKey:`${c.id}:${profileVersion}:rule_based`,summary:'',products:p.length?p:['other'],countries:found,topics:[/humanoid|휴머노이드/i.test(text)?'휴머노이드':/AI|인공지능|artificial intelligence/i.test(text)?'AI·인공지능':/actuator|액추에이터|controller|컨트롤러/i.test(text)?'구동·제어':/협동|cobot/i.test(text)?'협동로봇':'산업 동향'],score,method:'rule_based',evidenceScope:'metadata',reasons:[p.length?`입력 텍스트에서 ${p.map(k=>products[k]).join(', ')} 키워드 확인`:'제품 키워드 확인되지 않음',found.length?`국가 키워드: ${found.map(k=>countries[k]).join(', ')}`:'소재지·시장 정보 확인 필요'],facts:[],actions:[],unknowns:['제품 사양, 구매 의향 및 공급 관계는 원문 확인이 필요합니다.'],profileVersion,status:'completed'};}
export type Filters={q:string;type:string;period:string;countries:string[];products:string[];topic:string;relevance:string;status:string;sort:string;from:string;to:string};
export const defaults:Filters={q:'',type:'all',period:'7',countries:[],products:[],topic:'all',relevance:'all',status:'all',sort:'latest',from:'',to:''};
export function filterItems(items:Item[],f:Filters,now=Date.now()){return items.filter(c=>{const a=c.analysis;const q=f.q.trim().toLowerCase();if(q&&!`${c.title} ${c.titleKo} ${c.description} ${c.source} ${a?.summary||''}`.toLowerCase().includes(q))return false;if(f.type!=='all'&&f.type!==c.type)return false;if(f.countries.length&&!f.countries.some(k=>a?.countries.includes(k)))return false;if(f.products.length&&!f.products.some(k=>a?.products.includes(k as never)))return false;if(f.topic!=='all'&&!a?.topics.includes(f.topic))return false;if(f.relevance!=='all'&&(a?.score==null||(f.relevance==='high'?a.score<70:f.relevance==='medium'?a.score<40||a.score>69:a.score>39)))return false;if(f.status!=='all'&&(a?.status||'pending')!==f.status)return false;if(f.period!=='all'){if(!c.publishedAt)return false;const t=Date.parse(c.publishedAt);if(f.period==='custom'){if(f.from&&t<Date.parse(`${f.from}T00:00:00+09:00`))return false;if(f.to&&t>=Date.parse(`${f.to}T00:00:00+09:00`)+86400000)return false;}else if(t<now-Number(f.period)*86400000||t>now)return false;}return true;}).sort((a,b)=>(f.sort==='score'?(b.analysis?.score??-1)-(a.analysis?.score??-1):0)||(Date.parse(b.publishedAt||'')||0)-(Date.parse(a.publishedAt||'')||0)||b.id.localeCompare(a.id));}
export function dateLabel(value:string|null){return value?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'발행일 미상';}
export function loadUI(){try {const v=JSON.parse(localStorage.getItem('bcr:ui:v1')||'{}');return v.schemaVersion===1?v:{};}catch{return {};}}
export function saveUI(value:object){try{localStorage.setItem('bcr:ui:v1',JSON.stringify({schemaVersion:1,...value}));}catch{/* Content storage is independent. */}}
