import type { Backup, Content } from '../shared/schemas';
import { classify, dedup } from './domain';
export function createSeed():Backup{const now=new Date().toISOString();const workspace={id:crypto.randomUUID(),displayName:'심수정',createdAt:now};const entries=[
 ['news','북유럽 협동로봇 시장, 차세대 자동화의 기회를 열다','Nordic cobots: a new chapter in industrial automation','The Robot Report','DK','actuator','협동로봇','북유럽 제조 현장에서 유연한 자동화에 대한 관심이 커지고 있습니다. 협동로봇용 액추에이터와 정밀 구동 솔루션의 적용 가능성을 살펴보는 예시 자료입니다.','photo-1565043589221-1a6fd9ae45c7',90],
 ['news','ABB, 차세대 로봇 컨트롤러로 스마트 팩토리 혁신 가속','Next-generation robot control for the smart factory','ABB Robotics','SE','controller','산업용 로봇','스웨덴의 산업 자동화 시장과 로봇 제어 기술의 변화를 살펴봅니다. 고도화된 모션 제어와 에너지 효율이 핵심 검토 항목입니다.','photo-1581092921461-eab62e97a780',80],
 ['video','휴머노이드의 움직임을 만드는 핵심, 정밀 액추에이터','Inside the motion: precision actuators for humanoids','Robotics Insider','US','actuator','휴머노이드','휴머노이드 관절의 구동 구조와 액추에이터 역할을 소개하는 영상 메타데이터 예시입니다. 실제 영상 대본을 분석한 자료가 아닙니다.','photo-1485827404703-89b55fcc595e',70],
 ['news','덴마크 로봇 생태계, 글로벌 파트너십의 허브로','Denmark’s robotics ecosystem and global partnerships','Odense Robotics','DK','actuator','시장 동향','덴마크 로봇 생태계의 기업 협업과 부품 공급망을 검토하는 샘플입니다. 현지 파트너 발굴을 위한 조사 항목을 정리했습니다.','photo-1581092160562-40aa08e78837',90],
 ['video','생산 라인에서 만나는 차세대 협동로봇','Collaborative automation on the production floor','Universal Robots','DK','controller','협동로봇','협동로봇을 활용한 제조 공정 자동화 소개 자료입니다. 도입 환경과 제어 시스템 연동을 검토할 수 있습니다.','photo-1565043589221-1a6fd9ae45c7',80],
 ['news','독일 제조업의 로봇 자동화, 정밀 제어 수요를 읽다','Precision motion in German industrial automation','Automate.org','DE','controller','산업용 로봇','독일 제조 현장의 정밀 제어 수요와 생산 자동화 방향을 살펴보는 샘플입니다. 세부 도입 계획은 확인되지 않았습니다.','photo-1581092921461-eab62e97a780',60],
 ['news','한국 로봇 부품 산업, 글로벌 시장을 향한 도전','Korean robotics components and the global market','로봇신문','KR','actuator','시장 동향','국내 로봇 부품사의 해외 진출에 필요한 제품 인증과 공급망 검토 항목을 담은 예시 자료입니다.','photo-1485827404703-89b55fcc595e',60],
 ['video','물류 자동화의 다음 단계: 이동 로봇과 제어 기술','Mobile robots and warehouse automation','Robotics Insider','FI','controller','물류 로봇','핀란드 물류 자동화 시장을 가정한 영상 소개 샘플입니다. 이동 로봇의 제어 기술을 검토하기 위한 참고 구조를 제공합니다.','photo-1581092160562-40aa08e78837',70],
];const contents:Content[]=entries.map((e,i)=>({id:crypto.randomUUID(),type:e[0] as 'news'|'video',titleKo:String(e[1]),title:String(e[2]),source:String(e[3]),url:['https://www.therobotreport.com/nordic-cobots-sample/','https://new.abb.com/products/robotics/sample-controller','https://www.youtube.com/@BostonDynamics','https://www.odenserobotics.dk/ecosystem-sample/','https://www.youtube.com/@UniversalRobots','https://www.automate.org/news/german-automation-sample','https://www.irobotnews.com/korean-components-sample/','https://www.youtube.com/@ABBRobotics'][i],description:String(e[7]),image:`https://images.unsplash.com/${e[8]}?auto=format&fit=crop&w=1000&q=85`,dedupKey:'',publishedAt:`2026-09-${String(17-Math.floor(i/3)).padStart(2,'0')}T0${2+i%3}:00:00.000Z`,collectedAt:now,checkedAt:now,dataOrigin:'sample',duration:e[0]==='video'?['12:48','08:32','06:15'][i%3]:undefined,contentHash:`sample-v1-${i}`}));contents.forEach(c=>c.dedupKey=dedup(c.type,c.url));const analyses=contents.map((c,i)=>({...classify(c,1),method:'prepared' as const,analysisKey:`${c.id}:1:prepared`,summary:c.description,score:Number(entries[i][9]),countries:[String(entries[i][4])],products:[entries[i][5] as 'actuator'|'controller'],topics:[String(entries[i][6])],reasons:['제품 키워드와 대상 시장을 기준으로 구성한 예시 관련도입니다.'],facts:[],actions:['해당 출처에서 최신 원문을 확인한 뒤 잠재 고객과의 연관성을 검토하세요.'],unknowns:['이 자료는 기능 시연용으로 작성된 샘플이며 실제 보도 내용을 검증하지 않았습니다.','구체적인 성능 적합성·구매 의향·공급 관계는 확인되지 않았습니다.']}));const sources=contents.slice(0,6).map(c=>({id:crypto.randomUUID(),name:c.source,type:c.type,url:c.url,enabled:true,lastSuccessAt:null}));return {app:'bcr-robotics-radar',schemaVersion:1,exportedAt:now,workspace,contents,analyses,sources,contentSources:contents.slice(0,6).map((c,i)=>({contentId:c.id,sourceId:sources[i].id})),bookmarks:[],notes:[],companyProfiles:[{version:1,description:'블루클라우드 로보틱스는 로봇용 액추에이터와 컨트롤러를 제공하는 기업입니다. 북유럽 로봇 제조사와 자동화 기업의 동향을 파악하고 영업 기회를 탐색합니다.',products:['액추에이터','컨트롤러'],countries:['DK','SE','NO','FI'],createdAt:now}]};}
